### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by Nzzyme** [henry-richard7/Go-Voot-Streamer#1]
Hey, getting this page when I open this in web browser (http://localhost:8080/player?url=https://www.voot.com/movies/petta/962823)

Another Ex: http://localhost:8080/player?url=https://www.voot.com/shows/crackdown/293894

Screenshot: https://prnt.sc/1r7sqq3

**Comment by henry-richard7** [comment]
Did you run the server?

**Comment by Nzzyme** [comment]
> Did you run the server?

Oops, sorry. My bad

BTW, how do I run that go file?

**Comment by henry-richard7** [comment]
You have golang installed?
To run just download this repo, open terminal in that directory and use this command **go run Go-Voot-Streamer.go**

**Comment by Nzzyme** [comment]
Thanks for that. I downloaded and installed golang. Later, I opened the terminal in the directory in which the repo is and got this message 

https://prnt.sc/1r9rwd4

**Comment by henry-richard7** [comment]
Hey, I have compiled it to an executable file you can download from [here](https://github.com/henry-richard7/Go-Voot-Streamer/releases/download/1.0/Voot.Streamer.zip)

Extract the zip and run the **Voot Streamer.exe**
After running the exe file go to -> http://localhost:8080/player?url=https://www.voot.com/movies/petta/962823

Hope it works!

**Comment by Nzzyme** [comment]
Thank you! I tried this and it works with the link that you provided. When I tried with other 'Select' links, it doesn't work:
Es: http://localhost:8080/player?url=https://www.voot.com/shows/illegal/1/940138/justice-delayed-justice-denied/937867

Does it only stream the free stuff from Voot or even the paid premium shows/movies?

**Comment by henry-richard7** [comment]
You can watch premium movies, but some tv shows might not play.

**Comment by Nzzyme** [comment]
Ok, thanks!
